N = 5

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
  end

  (1..N).each do |i|
    config.vm.define "ubuntu-server-#{i}" do |us|
      us.vm.hostname = "ubuntu-server-#{i}"
      us.vm.provider :libvirt do |libvirt, override|
        libvirt.memory = 2048
        libvirt.nested = true
        libvirt.cpus = 2
      end

      us.ssh.insert_key = true
      us.ssh.port = 22
      us.ssh.compression = true
    end
  end
end
