# -*- mode: ruby -*-
# vi: set ft=ruby :
#

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |libvirt|
    libvirt.qemu_use_session = false
  end

  config.vm.define "virt-simple" do |rootNode|
   rootNode.vm.hostname = "virt-simple"
    rootNode.vm.provider :libvirt do |libvirt, override|
      libvirt.memory = 2048 
      libvirt.nested = true
      libvirt.cpus = 2
    end

    rootNode.ssh.insert_key = true
    rootNode.ssh.port = 22
    rootNode.ssh.compression = true
  end
end

